<table align="center" width=100%>
    <tr>
        <td width="20%">
            <img src="in-class.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> Inclass - Lab <br>(Day 1)
                    </b>
                </font>
            </div>
        </td>
        <td width="25%">
            <img src="GL-2.png">
        </td>
    </tr>
</table>

##  Table of Content

1. **[One Dimensional Array](#1D)**
2. **[Two Dimensional Array](#2D)**
3. **[For Loop](#For Loop)**

**Import the NumPy library before solving the exercises**

### Let's begin with some hands-on practice exercises

In [1]:
import numpy as np

<a id="1D"> </a>
## 1. One Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below: (or create your own list)**<br>

    list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]

In [2]:
# type your code here
list_temperature = [3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
ar1=np.array(list_temperature)
ar1

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

In [2]:
lt=[3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68]
a1=np.array(lt)
a1

array([3.04, 1.65, 5.76, 1.66, 1.54, 4.69, 2.68])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Create a 1D array of weights of 10 students and retrieve all the weights greater than 68</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the weights given below: (or create your own list)**

    weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]

In [4]:
# type your code here
weights = [74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
a1=np.array(weights)
a1
a1[a1>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

In [4]:
wt=[74.2, 85, 74, 67.9, 52, 70.5, 86, 51.8, 64, 82]
a2=np.array(wt)
a2
a2[a2>68]

array([74.2, 85. , 74. , 70.5, 86. , 82. ])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Write a code to generate 10 random integers between 20 to 40 (Is it possible to generate same random numbers everytime? If yes, describe the function)
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [11]:
# type your code here

#it is possible to generate same number every time with the help of seed
np.random.seed(5)
np.random.randint(20,40,10)

array([23, 34, 35, 26, 36, 29, 28, 24, 27, 36])

In [5]:
np.random.randint(20,40,10)

array([36, 29, 26, 35, 36, 30, 32, 25, 36, 35])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Write a program to get the fifth power of the first five positive integers
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [17]:
a3=np.arange(1,6)
res=np.power(a3,5)
res

array([   1,   32,  243, 1024, 3125], dtype=int32)

In [8]:
a3=np.arange(1,6)
r=np.power(a3,5)
r

array([   1,   32,  243, 1024, 3125], dtype=int32)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Write a program to create an array of all the odd integers from 50 to 100 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [12]:
# type your code here
np.arange(51,101,2)

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
np.arange(51,100,2)

array([51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83,
       85, 87, 89, 91, 93, 95, 97, 99])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Write a program to calculate the sum of each column </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below: (or create your own array)**

    A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]

In [23]:
# type your code here
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
a5=np.array(A)
a5
a5.sum(axis=0)

array([15, 25, 13])

In [11]:
A = [[1, 4, 8], [5, 7, 3], [9, 14, 2]]
a5=np.array(A)

a5.sum(axis=0)

array([15, 25, 13])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. Write a code to get the element-wise remainder of an array after division by 8 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**<br>
    
    num = [42, 87, 90, 14, 32, 75, 61, 80, 92]

In [15]:
# type your code here
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
a6=np.array(num)
a6
[a6%8]

[array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)]

In [16]:
num = [42, 87, 90, 14, 32, 75, 61, 80, 92]
a6=np.array(num)
[a6%8]

[array([2, 7, 2, 6, 0, 3, 5, 0, 4], dtype=int32)]

<a id="2D"> </a>
## 2. Two Dimensional Array

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Create a 2D numpy array from a 1D array of 20 elements of your choice. Further, subset the first 5 elements from the second element of a resulting 2D array 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [17]:
# type your code here
a7=np.random.randint(10,100,20).reshape(4,5)
a7
a7[1:2,:]

array([[69, 79, 20, 87, 64]])

In [21]:
a7=np.random.randint(10,50,20).reshape(4,5)
a7
a7[1:2,:]

array([[17, 12, 20, 17, 15]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Write a program to find common values between two arrays 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    prices_monday = [10, 30, 50, 60, 90]

    prices_tuesday = [50, 20, 80, 125, 10, 70]

In [18]:
# type your code here
a = [10, 30, 50, 60, 90]
b = [50, 20, 80, 125, 10, 70]
a8=np.array(a)
a9=np.array(b)
res=np.intersect1d(a8,a9)
res
#res=[i for i in a if i in b]
#res

array([10, 50])

In [22]:
prices_monday = [10, 30, 50, 60, 90]
prices_tuesday = [50, 20, 80, 125, 10, 70]
pm=np.array(prices_monday)
pt=np.array(prices_tuesday)
res=np.intersect1d(pm,pt)
res

array([10, 50])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Write a program to find BMI of the patients whose height and weight is provided in the list given below 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the lists given below:**<br>

    list of weights (in kg)
    weights = [57, 69, 54, 65 ,71, 62, 56]

    list of heights (in m)<br>
    heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 

In [19]:
# type your code here
weights = [57, 69, 54, 65 ,71, 62, 56]
w=np.array(weights)
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 
h=np.array(heights)
bmi=np.round(w/(h**2),2)
bmi


array([22.55, 22.53, 19.6 , 21.47, 26.4 , 20.96, 23.92])

In [24]:
weights = [57, 69, 54, 65 ,71, 62, 56]
heights = [1.59, 1.75, 1.66, 1.74, 1.64, 1.72, 1.53] 
wt=np.array(weights)
ht=np.array(heights)
bmi=np.round(wt/(ht**2),2)
bmi

array([22.55, 22.53, 19.6 , 21.47, 26.4 , 20.96, 23.92])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>11. Write a code to print the identity matrix of order 5</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [4]:
# type your code here
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>12. Write a program to transpose a matrix 
                    </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the matrix given below:**
    
    M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]

In [5]:
# type your code here
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
np.transpose(M)

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

In [26]:
M = [[15, 17, 45, 56], [7, 42, 15, 63], [54, 3, 61, 41], [0, 87, 16, 20]]
np.transpose(M)

array([[15,  7, 54,  0],
       [17, 42,  3, 87],
       [45, 15, 61, 16],
       [56, 63, 41, 20]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>13. Define a for loop to apply the function (2x-1)/(x+5) on every element of an array </b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the list given below:**
    
    numbers = [6, 5, 3, 15]

In [9]:
# type your code here
numbers = [6, 5, 3, 15]
a9=np.array(numbers)
a9
for i in range(len(a9)):
    a9[i]=(2*a9[i]-1)/(a9[i]+5)
a9

array([1, 0, 0, 1])

In [27]:
numbers = [6, 5, 3, 15]
a8=np.array(numbers)
for i in range(len(a8)):
    a8[i]=(2*a8[i]-1)/(a8[i]+5)
a8

array([1, 0, 0, 1])

In [26]:
x=np.array([6,5,3,15])
(2*x-1)/(x+5)

array([1.   , 0.9  , 0.625, 1.45 ])

In [21]:
mat=np.identity(5,dtype=int)
mat

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
[[1 if j==i else 0 for j in range(5)] for i in range(5) ]

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]